### ISSUE TITLE
Thx for your awesome work, I want to ask some questions

### ISSUE THREAD

**Issue by meiguoofa** [Yan98/S2FGAN#2]
1. If I only need reconstruction from the sketch(needn't attribute change), How should I sample it?
2. I trained on my datasets, but in the training process, the generated result from different sketches tend to be the same, it's bizarre, so can you give me some suggestions?
I will very much appreciate your help!
Thanks!

**Comment by Yan98** [comment]
Hi,
Thanks for your interest in our work. 
1. Please refer to https://github.com/Yan98/S2FGAN/blob/main/model.py#L1040
2. This also sounds weird to me. Will chang the weight of outer_bce and outer_edit help?  https://github.com/Yan98/S2FGAN/blob/main/model.py#L1029 and https://github.com/Yan98/S2FGAN/blob/main/model.py#L1090. From memory, this loss did help attribute editing, but will damage the image fidelity when training for long iterations.

**Comment by meiguoofa** [comment]
thanks for your reply!!!!!
